Implement goingCount(like-count)
OoreFasawe/ThrowIT pull request #1
Opened 2022-07-13 18:59 UTC by OoreFasawe

Throwers and users can now see how many people are attending a party, users can also see their availability changes real time when they click on the "going/ maybe/ not going" button.

2022-07-14 03:34 UTC, jcarlos1202 requested changes
Please address the comments and request the review again.

2022-07-14 03:34 UTC, jcarlos1202 commented on ThrowIT/ViewComponents/PartyCell.m
> +
remove this empty line

2022-07-14 03:34 UTC, jcarlos1202 commented on ThrowIT/ViewComponents/PartyCell.m
> +
remove this empty line

2022-07-14 03:34 UTC, jcarlos1202 commented on ThrowIT/ViewControllers/ThrowerTimelineViewController.m
> +    //    throwerPartyCell.numberAttendingParty.text = [NSString stringWithFormat:@"%d", party.numberAttending];
Remove commented code
```suggestion
```

2022-07-14 03:34 UTC, jcarlos1202 commented on ThrowIT/ViewControllers/TimelineViewController.m
> +//    partyCell.partyTime.text = party.partyDescription;
```suggestion
```

2022-07-14 03:34 UTC, jcarlos1202 commented on ThrowIT/ViewControllers/TimelineViewController.m
> +        //self.goingListCount = (int)partyGoingList.count;
```suggestion
```

2022-07-14 03:34 UTC, jcarlos1202 commented on ThrowIT/ViewControllers/TimelineViewController.m
> +    [partyQuery whereKey:@"attendanceType" equalTo:@"Going"];
Could we create an utility file with all the constants and use them instead of the hardcoded strings?

2022-07-15 18:01 UTC, patrickjamespacheco commented on ThrowIT/Models/Party.h
> +@property (nonatomic) int numberAttending;
to keep the Obj-C syntax, we should keep this as NSNumber and leave the "@(1)" syntax below or use NSInteger instead

2022-07-15 18:01 UTC, patrickjamespacheco commented on ThrowIT/ViewControllers/TimelineViewController.m
> +    [partyQuery whereKey:@"attendanceType" equalTo:@"Going"];
+1 to this. this will make changes in the future much easier

2022-07-16 02:11 UTC, jcarlos1202 approved these changes
Thanks! Looks good to me!

2022-07-16 19:38 UTC, merged